from bots_platform.gui.spaces.columns import Columns
from bots_platform.gui.spaces.login_space import LoginSpace
from bots_platform.gui.spaces.balance_space import BalanceSpace
from bots_platform.gui.spaces.markets_space import MarketsSpace
from bots_platform.gui.spaces.trading_space import TradingSpace
from bots_platform.gui.spaces.trading_bots_space import TradingBotsSpace
from bots_platform.gui.spaces.graphs_space import GraphsSpace
from bots_platform.gui.spaces.log_space import LogSpace
from bots_platform.gui.spaces.user_space import UserSpace
